<a href="https://colab.research.google.com/github/sarabjeet050/Learning_Python/blob/main/5_2_Numpy2D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Get to know Numpy Array
# import Numpy library
import numpy as np
# Use numpy 2D array A :
A = np.array([[11, 12], [21, 22], [31, 32]])
print(A)

[[11 12]
 [21 22]
 [31 32]]


In [ ]:
# Find the type of A using function type()
print(type(A))

<class 'numpy.ndarray'>


In [ ]:
# Find the shape of A
print(A.shape)

(3, 2)


In [ ]:
# Find the type of data in A
print(A.dtype)

int64


In [ ]:
# Find second row of numpy array A
print(A[1])

[21 22]


#### Two Types of Multiplication

In [ ]:
# Use following numpy arrays:
A = np.array([[11, 12], [21, 22]])
B = np.array([[1, 0], [0, 1]])
print(A)
print(B)

[[11 12]
 [21 22]]
[[1 0]
 [0 1]]


In [ ]:
# Multiply Array A and B or Hadamard Multiplication
print(np.multiply(A, B))
print(A * B)

[[11  0]
 [ 0 22]]
[[11  0]
 [ 0 22]]


In [ ]:
# Perform matrix multiplication  on array A and B (order will not matter)
print(np.dot(A, B))

[[11 12]
 [21 22]]


#### Create 2D Numpy Array

In [ ]:
# import the libraries
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
# Consider list a, which contains 3 nested lists each of equal size
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
print(a)

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]


In [ ]:
# Create list to Numpy Array
# Each element is the same type

A = np.array(a)
print(A)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
# Use ndim to obtain the number of axes or dimensions, referred to as rank
# Show the numpy array dimension
print(A.ndim)

2


In [ ]:
# Attribute shape returns a tuple corresponding to size or number of each dimension (R , C)
# Show the numpy array shape
print(A.shape)

(3, 3)


In [ ]:
# The total number of elements in the numpy array is given by attribute size (R*C)
# Show the numpy array size
print(A.size)

9


#### Accessing different elements of Numpy Array
###### Use rectangular brackets to access elements of array just like list. For eg: Array_name[Row_index, column_index]

In [ ]:
# Access the element on 2nd row and 3rd column
print(A[1, 2])

23


In [ ]:
# Can also use nested list concept for access element in 2D
print(A[1][2]) # array_name[row_index][col_index]

23


In [ ]:
# Access element on 1st row and 1st column
print(A[0, 0])

11


In [ ]:
# Can also slice in numpy arrays.
# Access the element on 1st row and 1st, 2nd columns

print(A[0][0:2])

[11 12]


In [ ]:
# Access element on 1st and 2nd row and 3rd column
print(A[0:2,2])

[13 23]


#### Basic Operations

In [ ]:
# Can add arrays. This process is identical to matrix addition.

In [ ]:
# Create a numpy array X
X = np.array([[1, 0], [0, 1]])
print(X)

[[1 0]
 [0 1]]


In [ ]:
# Create a numpy array Y
Y = np.array([[2, 1], [1, 2]])
print(Y)

[[2 1]
 [1 2]]


In [ ]:
# Can add numpy arrays:
Z = X + Y
print(Z)

[[3 1]
 [1 3]]


In [ ]:
# Multiply to a numpy array by a scalar is identical to multiplying a matrix by a scalar.
# If we multiply the matrix Y by a scalar 2, we simply multiply every element in the matrix
# by scalar 2

In [ ]:
# Create a numpy array X
X = np.array([[2, 1], [1, 2]])
print(X)

[[2 1]
 [1 2]]


In [ ]:
# Mulptiply Y with scalar 2
Z = Y * 2
print(Z)

[[4 2]
 [2 4]]


In [ ]:
# Multiplication of 2 arrays corresponds to element-wise product or Hadamard product
# Hadamard product corresponds to multiplying each of elements in same position.
# The result is new matrix that is of same size as of X and Y

In [ ]:
# Create a numpy array Y
Y = np.array([[2, 1], [1, 2]])
print(Y)

[[2 1]
 [1 2]]


In [ ]:
# Create a numpy array X
X = np.array([[1, 0], [0, 1]])
print(X)

[[1 0]
 [0 1]]


In [ ]:
# Perform element-wise product of array X and Y
Z = X * Y
print(X)

[[1 0]
 [0 1]]


In [ ]:
# Matrix Multiplication with the numpy array A and B

In [ ]:
# Create a matrix A
A = np.array([[0, 1, 1], [1, 0, 1]])
print(A)

[[0 1 1]
 [1 0 1]]


In [ ]:
# Create a matrix B
B = np.array([[1, 1], [1, 1], [-1, 1]])
print(B)

[[ 1  1]
 [ 1  1]
 [-1  1]]


In [ ]:
# Use numpy function dot to multiply array together
Z = np.dot(A, B)
print(Z)

[[0 2]
 [0 2]]


In [ ]:
# Calculate sine of Z
print(np.sin(Z))

[[0.         0.90929743]
 [0.         0.90929743]]


In [ ]:
 # Use numpy attribute T to calculate the transponsed matrix

In [ ]:
# Create matrix C
C = np.array([[1, 1], [2, 2], [3, 3]])
print(C)

[[1 1]
 [2 2]
 [3 3]]


In [ ]:
# Get the transpose of C
print(C.T)
print()
print(C.transpose())

[[1 2 3]
 [1 2 3]]

[[1 2 3]
 [1 2 3]]


#### Quiz on 2D Numpy array

In [ ]:
# Consider following list a and convert it to numpy array
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
print(a)
A = np.array(a)
print(A)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Calculate the numpy array size
print(A.size)

12


In [48]:
# Access the element on first row and first and second column
print(A[0][0:2])
print(A[0, 0:2])

[1 2]
[1 2]


In [49]:
# Perform the matrix multiplication with numpy arrays A and B
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
print(B)

C = np.dot(A, B)
print(C)

[[ 0  1]
 [ 1  0]
 [ 1  1]
 [-1  0]]
[[ 1  4]
 [ 5 12]
 [ 9 20]]
